# Generated by Django 3.0.2 on 2020-01-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
