# Generated by Django 3.0.2 on 2020-01-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_disco_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='precio',
            field=models.IntegerField(default=0, verbose_name=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disquera',
            name='direccion',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disquera',
            name='sitioweb',
            field=models.URLField(default='http://localhost:8000'),
            preserve_default=False,
        ),
    ]
