# Generated by Django 3.0.2 on 2020-01-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20200113_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
