# Generated by Django 3.0.2 on 2020-01-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_artista_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='precio',
            field=models.FloatField(),
        ),
    ]
